[workspace]
members = [
"diesel_derives_extra",
"diesel_derives_traits"
]

[replace]
"diesel_derives_extra:0.1.3" = { path = "diesel_derives_extra" }
"diesel_derives_traits:0.1.3" = { path = "diesel_derives_traits" }
