[package]
name = "diesel_derives_traits"
description = "Traits for diesel_derives_extra"
homepage = "https://git.onewebdev.info/soichiro/diesel_derives"
license = "MIT"
repository = "https://git.onewebdev.info/soichiro/diesel_derives"
version = "0.1.0"
authors = ["Josh Holmer <jholmer.in@gmail.com>"]

[dependencies]

[dependencies.clippy]
optional = true
version = "*"

[dependencies.diesel]
features = ["postgres"]
version = "1.0.0-beta1"
