[package]
authors = ["Josh Holmer <jholmer.in@gmail.com>"]
description = "Automatically derive some simple CRUD methods for your Diesel models"
exclude = [
    "tests/*",
]
homepage = "https://github.com/shssoichiro/diesel-derives-extra"
license = "MIT"
name = "diesel_derives_extra"
repository = "https://github.com/shssoichiro/diesel-derives-extra"
version = "0.1.1"

[lib]
name = "diesel_derives_extra"
proc-macro = true

[dependencies]
quote = "0.3.15"
syn = "0.11.11"

[dependencies.clippy]
optional = true
version = "0.0.150"

[dependencies.diesel]
features = ["postgres"]
version = "1.0.0"

[dependencies.diesel_derives_traits]
version = "0.1.1"
