[package]
authors = ["Josh Holmer <jholmer.in@gmail.com>"]
description = "Automatically derive some simple CRUD methods for your Diesel models"
exclude = [
    "tests/*",
]
homepage = "https://git.onewebdev.info/soichiro/diesel_derives"
license = "MIT"
name = "diesel_derives_extra"
repository = "https://git.onewebdev.info/soichiro/diesel_derives"
version = "0.1.0"

[lib]
name = "diesel_derives_extra"
proc-macro = true

[dependencies]
quote = "0.3.15"
syn = "0.11.11"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.diesel]
features = ["postgres"]
version = "1.0.0-beta1"

[dependencies.diesel_derives_traits]
version = "0.1.0"
